In [3]:
import pandas as pd

df = pd.read_csv('gapminder_simple.csv')
df.head()

         country  year         pop continent  lifeExp    gdpPercap
0        Myanmar  1962  23634436.0      Asia   45.108   388.000000
1        Ireland  1957   2878220.0    Europe   68.900  5599.077872
2        Jamaica  1977   2156814.0  Americas   70.110  6650.195573
3  Cote d'Ivoire  1987  10761098.0    Africa   54.655  2156.956069
4        Morocco  1997  28529501.0    Africa   67.660  2982.101858

# Step 1: Projection

In [4]:
use_cols = ['country', 'continent', 'year', 'lifeExp', 'gdpPercap']
df1 = df[use_cols].copy()

df1.head()

         country continent  year  lifeExp    gdpPercap
0        Myanmar      Asia  1962   45.108   388.000000
1        Ireland    Europe  1957   68.900  5599.077872
2        Jamaica  Americas  1977   70.110  6650.195573
3  Cote d'Ivoire    Africa  1987   54.655  2156.956069
4        Morocco    Africa  1997   67.660  2982.101858

In [8]:
mask = (df1['continent'] == 'Asia') & (df1['year'].isin([1990, 2007]))

asia_1990_2007 = df.loc[mask, ['country', 'continent', 'year', 'lifeExp', 'gdpPercap', 'pop']].copy()
# asia_1990_2007 = df1[mask].copy()
asia_1990_2007.head()

          country continent  year  lifeExp     gdpPercap           pop
40          India      Asia  2007   64.698   2452.210407  1.110396e+09
300       Myanmar      Asia  2007   62.069    944.000000  4.776198e+07
313         Nepal      Asia  2007   63.785   1091.359778  2.890179e+07
326    Bangladesh      Asia  2007   64.062   1391.253792  1.504483e+08
421  Saudi Arabia      Asia  2007   72.777  21654.831940  2.760104e+07